name: Deploy Application Coffeebreak

on:
    push:
        branches: [main]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create Setup Java
              uses: actions/java-setup-java@v3
              with:
                distribution: 'temorin'
                java-version: '17'
            - name: Build project
              run: mvn clean install 



                    